apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmap.yml
  - pvcs.yml
  - qdrant.yml
  # - ollama.yml
  # - open-webui.yml
  # - tei.yml
  # - tei-reranker.yml
  # - tei-splade.yml
  - ingress.yml
