apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: ai-platform
  labels:
    app.kubernetes.io/part-of: ai-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
#---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: open-webui-data
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ollama-data
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 50Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hf-cache
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 20Gi
