apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmap.yml
  - pvcs.yml
  - azurite.yml
  - cosmosdb.yml
  # - sqlserver.yml
  # - eventhubs.yml
  # - servicebus.yml
  # - appconfig.yml
