apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yml
  - pvcs.yml
  - kafka-broker-1.yml
  - kafka-broker-2.yml
  - kafka-broker-3.yml
  - nodeport.yml
