apiVersion: v1
kind: Service
metadata:
  name: kafka-ext-broker-1
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
spec:
  type: NodePort
  selector:
    app: kafka-broker-1
  ports:
    - name: kafka-broker-1
      port: 9092
      targetPort: 9092
      nodePort: 30092