apiVersion: v1
kind: Service
metadata:
  name: kafka-ext-broker-2
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
spec:
  type: NodePort
  selector:
    app: kafka-broker-2
  ports:
    - name: kafka-broker-2
      port: 9093
      targetPort: 9093
      nodePort: 30093