apiVersion: v1
kind: Service
metadata:
  name: kafka-ext-broker-3
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
spec:
  type: NodePort
  selector:
    app: kafka-broker-3
  ports:
    - name: kafka-broker-3
      port: 9095
      targetPort: 9095
      nodePort: 30095