apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-platform-config
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
data:
  # Zookeeper
  ALLOW_ANONYMOUS_LOGIN: "yes"
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"

  # Kafka Broker
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT_INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_INTERNAL://kafka-broker-1.kafka-platform.svc.cluster.local:19092,EXTERNAL://localhost:30092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_INTERNAL"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"

  # Schema Registry
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka-broker-1:19092"
  SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "PLAINTEXT"

  # Kafka UI
  KAFKA_CLUSTERS_0_NAME: "local"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker-1:19092"
  KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "PLAINTEXT"
  KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
  KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
  KAFKA_BROKERCONNECT: "kafka-broker-1:19092"
  DYNAMIC_CONFIG_ENABLED: "true"
