apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openobserve-platform-ingress
  namespace: openobserve-platform
  labels:
    app.kubernetes.io/part-of: openobserve-platform
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: openobserve.127.0.0.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openobserve
                port:
                  number: 5080
    - host: otel-collector.127.0.0.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otel-collector
                port:
                  number: 4318
