apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
  namespace: openobserve-platform
  labels:
    app: openobserve
    app.kubernetes.io/part-of: openobserve-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      containers:
        - name: openobserve
          image: openobserve/openobserve:latest
          ports:
            - containerPort: 5080
            - containerPort: 5081
          env:
            - name: ZO_DATA_DIR
              value: /data
            - name: ZO_ROOT_USER_EMAIL
              value: admin@example.com
            - name: ZO_ROOT_USER_PASSWORD
              value: ComplexPassword#123
          volumeMounts:
            - name: openobserve-data
              mountPath: /data
      volumes:
        - name: openobserve-data
          persistentVolumeClaim:
            claimName: openobserve-data
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: openobserve-platform
  labels:
    app: openobserve
    app.kubernetes.io/part-of: openobserve-platform
spec:
  type: ClusterIP
  selector:
    app: openobserve
  ports:
    - name: http
      port: 5080
      targetPort: 5080
    - name: http-alt
      port: 5081
      targetPort: 5081
